### PR TITLE
account for nested paths in packages

### PR DESCRIPTION
**Pull request by FynnBe**
as requested in https://github.com/bioimage-io/spec-bioimage-io/issues/96

### CODE REVIEW

**Comment by constantinpape** [comment]
What exactly does this do?

**Comment by FynnBe** [comment]
it allows to have folders inside a resource package, e.g. 

```yaml
documentation: nested/folder/README.md
```

```
# rdf.zip
- rdf.yaml
- nested
  - folder
    - README.md
```

same package on zenodo:
```
# rdf.zip
- rdf.yaml
- nested/folder/README.md
```

it worked surprisingly almost out of the box. Just needed to avoid using `file_path.name` and keep the whole relative path (relative to root_path) in the package content, etc.

**Comment by constantinpape** [comment]
So on zenodo the '/' is just treated as "virtual" folder similar to how object stores handle this?

**Review by constantinpape — APPROVED** [review]

**Comment by FynnBe** [comment]
> So on zenodo the '/' is just treated as "virtual" folder similar to how object stores handle this?

That's my current understanding of what @oeway said in #96

**Pull request merged**
