### PR TITLE
Generate docs and schema with github actions

### PR DESCRIPTION
**Pull request by oeway**
This PR uses github actions to generate both the docs and schema, the generated file will be stored in the [gh-pages branch](https://github.com/bioimage-io/spec-bioimage-io/tree/gh-pages). 

## Why use CI to generate?
I think this should be a better approach compared to pre-commit hooks which rely on certain setup and won't work for edit made directly in github website. It is also nice to separate the true source code from the generated files into different branches.

### CODE REVIEW

**Comment by oeway** [comment]
This PR is ready for preview.

**Review by FynnBe — APPROVED** [review]
very neat!

**Comment by oeway** [comment]
@FynnBe thanks for the review, these is an issue for running the generating json spec, if I enable the command, the CI fails said no module named bioimageio.spec..., but the wired thing is that the generate docs command runs without issue. Any idea?

**Comment by FynnBe** [comment]
> @FynnBe thanks for the review, these is an issue for running the generating json spec, if I enable the command, the CI fails said no module named bioimageio.spec..., but the wired thing is that the generate docs command runs without issue. Any idea?
> 
> Let's fix it in another PR

👍  I'll have a look at it soon

**Pull request merged**
