### PR TITLE
Update VERSION

### PR DESCRIPTION
**Pull request by constantinpape**
I think we should make a new release, now that @FynnBe has moved the more complex functionality to `bioimageio-python`

### CODE REVIEW

**Comment by k-dominik** [comment]
are we sure that bioimage.core PRs will not make any changes here necessary? We have tests there, that test against main branch here, and that still fail.

**Comment by constantinpape** [comment]
I think the tests vs. `main` are actually passing.

**Review by k-dominik — APPROVED** [review]
cool let's go ahead

**Comment by constantinpape** [comment]
> cool let's go ahead

Awesome! 
@FynnBe please go ahead and merge this if there are no objections from your side (i.e. nothing left in the refactoring that I forgot about)

**Pull request merged**
