### PR TITLE
Add a `type` and `version` key

### PR DESCRIPTION
**Pull request by oeway**
In the RDF definition we have the `type` and `version` key, it would be nice if we can add it for the models as well.

Todo: bump version and add changelog

### CODE REVIEW

**Review by constantinpape — APPROVED** [review]

**Comment by constantinpape** [comment]
@oeway I think all the changes in #79, #81, #82 and #83 make a lot of sense. But I suggest we introduce all of them in a single version bum from 0.3.1 to 0.3.2. That would make it easier to make actual releases on gh for these versions.

**Comment by oeway** [comment]
> @oeway I think all the changes in #79, #81, #82 and #83 make a lot of sense. But I suggest we introduce all of them in a single version bum from 0.3.1 to 0.3.2. That would make it easier to make actual releases on gh for these versions.

Agreed, I am thinking the same while I add more, will make sure I merge them.

**Comment by FynnBe** [comment]
let's not merge this, but incorporate it into #80

**Comment by FynnBe** [comment]
should the version be `None` if not present or should it be 0.1.0 (my favorite, so it's never None and always comparable)?

**Comment by oeway** [comment]
> should the version be `None` if not present or should it be 0.1.0 (my favorite, so it's never None and always comparable)?

No strong opinion here, and yes, I think we can default it to 0.1.0 if not present.

**Comment by FynnBe** [comment]
implemented in https://github.com/bioimage-io/spec-bioimage-io/pull/80/commits/d03984dd14af0afe4b2bd1ad0e6f4252beaa6d90 (part of #80)

**Pull request closed without merging**
