### PR TITLE
ImplicitShape for inputs and outputs (part 1 in 0.3)

### PR DESCRIPTION
**Pull request by FynnBe**
This PR changes implements the first set of changes discussed in #234 

also it:
- rename `ImplicitInputShape` to `ParametrizedInputShape` to avoid confusion

### CODE REVIEW

**Review by constantinpape — APPROVED** [review]
LGTM, do we want to bump the version in this PR already or do it in a separate one?

**Comment by constantinpape** [comment]
Also, we should add the change to the changelog once we bump the version.

**Comment by FynnBe** [comment]
> LGTM, do we want to bump the version in this PR already or do it in a separate one?

currently this PR already bumps it

**Comment by constantinpape** [comment]
Ok, I think this is all good now, @FynnBe please go ahead and merge yourself if you think all is ready here.

**Comment by FynnBe** [comment]
> > LGTM, do we want to bump the version in this PR already or do it in a separate one?
> 
> currently this PR already bumps it

oh, you probably already thought of the version in the VERSION file, while I was thinking of the model FormatVersion... I'll bump the VERSION for a release in a separate PR...

**Comment by constantinpape** [comment]
> > 
> 
> oh, you probably already thought of the version in the VERSION file, while I was thinking of the model FormatVersion... I'll bump the VERSION for a release in a separate PR...

Yes, that's what I meant.

**Comment by FynnBe** [comment]
https://github.com/bioimage-io/spec-bioimage-io/pull/237

**Pull request merged**
