### PR TITLE
Stricter name field

### PR DESCRIPTION
**Pull request by FynnBe**

### CODE REVIEW

**Comment by FynnBe** [comment]
closes #463

**Comment by FynnBe** [comment]
This PR bumps model RDF to 0.4.7 and other RDFs to 0.2.3, which do not allow any forward or backward slash in `name` fields other than `run_mode:name`

**Comment by FynnBe** [comment]
@oeway you can merge this if you need this. I'm off on vacation tomorrow, so I can't help with any unintended side effects. I'm careful here, because we have not bumped the general/collection/dataset RDF often yet...

**Comment by oeway** [comment]
No hurry, let's wait when you get back.

**Pull request merged**
