### PR TITLE
Add conda recipe

### LINKED ISSUE #137: FileNotFoundError licenses.json
@k-dominik Is this related to the recent change in the license?

https://github.com/imjoy-team/bioimage-io-models/runs/2889305580#step:5:27

### PR DESCRIPTION
**Pull request by k-dominik**
This PR adds a conda recipe and an entrypoint for the script (after installation users can `bioimageio verify-spec ....`

not all dependencies are on conda-forge yet, so this has to be build with our conda channel:

```bash
conda build -c ilastik-forge -c conda-forge conda-recipe
```

we'll host the package on `ilastik-forge` for now.

ideally #133 would be resolved before merging this

fixes #137

### CODE REVIEW

**Comment by constantinpape** [comment]
Just FYI, I forked https://github.com/bioimage-io/staged-recipes a while ago to prepare a conda-forge package, but did not work on it yet because the current release has some issues, see #114. It would be good to resolve this as well before pushing anything to conda.

> not all dependencies are on conda-forge yet

What is lacking from conda-forge?

**Comment by oeway** [comment]
I am not very familiar with how conda build the packages, can we automatically synchronise with CI? SO when we make aa new release, it automatically publish on pypi and conda. We have the CI template for pypi([example](https://github.com/imjoy-team/imjoy-python-template/blob/main/.github/workflows/release.yml)) but I don't know for conda-forge.

**Comment by constantinpape** [comment]
> I am not very familiar with how conda build the packages, can we automatically synchronise with CI?

Once we have the package on conda forge this is all done automatically by conda forge CI.
That's what https://github.com/bioimage-io/staged-recipes is for. However before we can submit a PR to conda-forge that adds spec-bioimageio as a conda forge package we need to fix the issues with the current release, see #114 and make sure that all dependencies are available on conda forge.

@k-dominik is working on a new ilastik release, that will need spec-bioimageio and we want to go ahead without waiting for the conda-forge package. So for now, he will build the package via the local recipe and put it on the ilastik conda channel.
As soon as we have fixed the issues with the release and all dependencies on conda we will migrate to conda forge (which will keep the package up-to-date automatically.)

**Comment by oeway** [comment]
That sounds good! Just make sure I understand it, after submitting to staged-recipes conda will automatically pull from a specified GitHub repo for updates? Or how does the synchronization works after we made a new release?

**Comment by constantinpape** [comment]
> That sounds good! Just make sure I understand it, after submitting to staged-recipes conda will automatically pull from a specified GitHub repo for updates? Or how does the synchronization works after we made a new release?

Once the recipe is merged into conda forge, a bot will frequently check the specified git repo for new releases and, when it finds a new release, submit a PR to the recipe (which will be a separate repository in the conda-forge org) to update the package.

This PR can then be merged by maintainers of the recipe (which are determined in the recipe metadata) and the updated package will be pushed to conda forge. (The recipe can also be configured s.t. updates by the bot are merged automatically if CI passes.)

**Comment by oeway** [comment]
I see, thanks! I will check how they implemented the bot, we might need something like that to synchronize community partner's repos.

**Comment by k-dominik** [comment]
> What is lacking from conda-forge?

right now marshmallow-jsonschema is still pending merge into conda-forge. I'm pretty sure it will be done by the end of the week. Once #114 is merged, and all dependencies are available on conda-forge, I can open the appropriate PR to get the package up.

ref: https://github.com/conda-forge/staged-recipes/pull/15361

**Comment by k-dominik** [comment]
re: CI, as @constantinpape this would be totally doable, but I'd also prefer to have conda-forge do the  work for us there.

**Comment by k-dominik** [comment]
ah, and maybe one _important_ question (naming things): I named this package `bioimageio.spec` :) Is that fine withe everyone?

**Review by FynnBe — APPROVED** [review]
LGTM

**Comment by FynnBe** [comment]
> ah, and maybe one important question (naming things): I named this package bioimageio.spec :) Is that fine withe everyone?

there is some magic with distributed packages. There should be the package `bioimageio` with the modules `spec` (+ more will follow, e.g. core). I think naming this package `bioimageio.spec` is correct. Otherwise the name would clash with `bioimageio.core` (or whatever we'll end up naming it)

**Comment by k-dominik** [comment]
> > ah, and maybe one important question (naming things): I named this package bioimageio.spec :) Is that fine withe everyone?
> 
> there is some magic with distributed packages. There should be the package `bioimageio` with the modules `spec` (+ more will follow, e.g. core). I think naming this package `bioimageio.spec` is correct. Otherwise the name would clash with `bioimageio.core` (or whatever we'll end up naming it)

While naming it like this is very logical, it is not necessary. bioimage is a namespace package - I think it would would work in any case because of internal folder structure (not 100% sure :))

**Comment by FynnBe** [comment]
@k-dominik is this ready to merge?

**Comment by k-dominik** [comment]
from my perspective this PR is finished, yes

**Pull request merged**
