### PR TITLE
version bump 0.3.2.rc0

### LINKED ISSUE #114: Move 0.3.2 tag
I think the 0.3.2 release was made pre-maturely and we need to move it due to:
- It did not have CI and the tests actually did not pass due to remaining issues in the spec, see #103 
- Parts of the python functionality did not work yet and are still not fully working, see #108 
- The validator uses marshmallow to validate the rdf instead of jsonschema, which will make all current rdfs fail, see #107. (Note that we are discussing switching to marshmallow as the reference for the rdf as well, BUT that requires a minor version bump.) (Also it' fine to validate with marshmallow, but we need to make sure that we are compliant with the current rdf spec.)

### PR DESCRIPTION
**Pull request by k-dominik**
I guess we could use this PR to try to discuss/establish a release workflow. We probably don't need to make a big discussion out of this.

There are always options, of course:

1) Change `VERSION` file, Open PR, wait for PR to be approved by (someone specific, N reviewers?), merge, tag - build on CI
2) Discuss (somewhere, BioimageIO meetings?), change `VERSION` file, Commit directly to master - tag - build on CI
3) get rid of version file, use something like versioneer to update version directly from tag. workflow: tag - build on CI.

by opening this PR you can probably see that I'm slightly in favor of 1)

Once this is merged, I'll remove the bare `0.3.2` tag (and rename `0.3.1` and `0.3.0` tags to `x.y.z-release0`)

closes #114

### CODE REVIEW

**Comment by constantinpape** [comment]
I guess we need to change to `0.3.2.rc0`.

Also note that @oeway added some CI for release drafting in https://github.com/bioimage-io/spec-bioimage-io/pull/151.
Not sure how this constraints us in terms of creating new releases.

**Comment by FynnBe** [comment]
> Also note that @oeway added some CI for release drafting in #151.
> Not sure how this constraints us in terms of creating new releases.

looks to me like the CI detects content changes in the VERSION file and tags and publishes if something has changed (and it's on  main)

the publshed package has version 0.3a0, so 0.3.2.rc0 should correctly  succeed

**Review by FynnBe — APPROVED** [review]

**Review by constantinpape — APPROVED** [review]
Ok, let's give it a try :D

**Comment by FynnBe** [comment]
I really hate to say this, but I do have second thought about matching the bioimageio.spec package version to the model RDF spec 🙅 
What happens when we develop another specific RDF (like 'dataset RDF') in the future? we might want to split the submodles into 'model' and 'dataset' and this would mean the bioimageio.spec version would really clash with developing the 'dataset RDF'.

Oh, the pain is real, but maybe it is the best to keep it a completely independen version, just for the package. A version that we can bump every time any of our RDF changes...

**Comment by FynnBe** [comment]
maybe our future structure for the whole package could be:

```
bioimageio.spec/
|-- shared/
|-- static/
|-- general_rdf/
|   |-- v0_2/
|   |-- v0_3/
|-- model_rdf/
|   |-- v0_1/
|   |-- v0_3/       # uses spec.general_rdf.v0_2
|   |-- v0_4/       # uses spec.general_rdf.v0_3
|-- dataset_rdf/
|   |-- v0_1/       # uses spec.general_rdf.v0_3
|-- __init__.py     # import all latest RDFs into bioimageio.spec  
|
```

This looks quite different, but is actually very close to the code right now...

**Comment by constantinpape** [comment]
> maybe our future structure for the whole package could be:

I think that's a good idea, but let's make a stable 0.3.2 release first!

**Comment by k-dominik** [comment]
merging this an hoping for the best! Remember, we can have as many releases as we want :o

**Comment by k-dominik** [comment]
wrong button

**Comment by oeway** [comment]
> I guess we need to change to `0.3.2.rc0`.
> 
> Also note that @oeway added some CI for release drafting in #151.
> Not sure how this constraints us in terms of creating new releases.

Nothing, if you change the version number, it will automatically create a release on github and publish on pypi.

It actually looks nice: https://github.com/bioimage-io/spec-bioimage-io/releases/tag/v0.3.2.rc0

**Pull request merged**
