### PR TITLE
Remove ruamel.yaml dependency

### PR DESCRIPTION
**Pull request by FynnBe**
ruamel.yaml is not supported by Pyodide, therefor we use PyYAML instead.

problem: PyYAML currently only supports yaml 1.1, whereas ruamel.yaml (what we used until now) defaults to yaml 1.2. 
Differences: https://yaml.readthedocs.io/en/latest/pyyaml.html#defaulting-to-yaml-1-2-support

The one difference that might be most relevant for us: "correct parsing of floating point scalars with exponentials" is added manually to the current ruamel.yaml replacement.
see https://github.com/yaml/pyyaml/issues/173 and https://stackoverflow.com/questions/30458977/yaml-loads-5e-6-as-string-and-not-a-number.

Also note that not all valid json is compatible with yaml 1.1 (but with yaml 1.2).

With this yaml 1.1/1.2 hybrid we should be good for now and can hopefully switch easily to the full yaml 1.2 in the future.

### CODE REVIEW

**Comment by FynnBe** [comment]
fixes #209

**Review by constantinpape — APPROVED** [review]
LGTM, feel free to merge.

**Comment by oeway** [comment]
@FynnBe Great! Could you make a new release so we can try it with pyodide?

**Comment by FynnBe** [comment]
sure, let's wait for https://github.com/bioimage-io/spec-bioimage-io/pull/214 to be merged and then go ahead with a little new release

**Pull request merged**
