### PR TITLE
resolve ids from BIOIMAGEIO_COLLECTION

### PR DESCRIPTION
**Pull request by FynnBe**
this PR implements:
 - on import of bioimageio.spec we try to resolve the BioImage.IO collection.json that holds all available resources on bioimage.io.
 - with all available ids, we then resolve a given id in `load_raw_resource_description` (or any other func that takes an rdf source) to point to our updated rdf.yaml in  https://github.com/bioimage-io/collection-bioimage-io/tree/gh-pages/rdfs

### CODE REVIEW

**Comment by FynnBe** [comment]
fixes https://github.com/bioimage-io/core-bioimage-io-python/issues/236

**Comment by FynnBe** [comment]
before we actually did not support any BioImage.IO other than those that happened to be valid doi (anything on zenodo). i.e. any partner resource id was never resolved.

currently this PR does not implement resolving partner ids that are only resource ids and not verison ids (wo the "/latest").

**Review by constantinpape — COMMENTED** [review]
I haven't looked at the changes in detail, but this looks fine.
We should add a test for this though.

**Comment by FynnBe** [comment]
> currently this PR does not implement resolving partner ids that are only resource ids and not verison ids (wo the "/latest").

[4d78314](https://github.com/bioimage-io/spec-bioimage-io/pull/410/commits/4d78314a296c707b24ee4937a4a71c48c6961caa) implements this

**Review by constantinpape — APPROVED** [review]
Looks good now, feel free to merge.

**Pull request merged**
