### PR TITLE
substitute stdnum.iso7064.mod_11_2.is_valid

### PR DESCRIPTION
**Pull request by FynnBe**
~~note: not on master but on #191~~

### CODE REVIEW

**Review by k-dominik — APPROVED** [review]
lgtm, was there a reason to get rid of this dep other than that we can?

**Comment by FynnBe** [comment]
> lgtm, was there a reason to get rid of this dep other than that we can?

reducing dependencies to make it easier to run in pyodide

**Comment by k-dominik** [comment]
> > lgtm, was there a reason to get rid of this dep other than that we can?
> 
> reducing dependencies to make it easier to run in pyodide

okay less deps are better deps ;) This is always nice! Although that one is Python only, so not much of an issue for pyodide.

**Comment by FynnBe** [comment]
true, it was just about overall package size to speed things up...

**Pull request merged**
