### PR TITLE
Add sample model that upscales input.

### PR DESCRIPTION
**Pull request by pattonw**
used for testing core-bioimage-io-python tiling works on models that have a scale factor

### CODE REVIEW

**Review by constantinpape — APPROVED** [review]
Thanks @pattonw. I will merge this despite the test error (it's unrelated to the changes here).

**Comment by FynnBe** [comment]
was too slow to comment:
would be great to include this model also in a static validation test here in spec... could we add that still?

**Comment by constantinpape** [comment]
> was too slow to comment:
> would be great to include this model also in a static validation test here in spec... could we add that still?

Yeah, makes sense. Can you make a follow up PR?

**Comment by FynnBe** [comment]
will do

**Comment by FynnBe** [comment]
> will do

see https://github.com/bioimage-io/spec-bioimage-io/pull/484

**Pull request merged**
