### PR TITLE
Release 0.3.2

### PR DESCRIPTION
**Pull request by constantinpape**
I think we have everything ready for this release now.
Any objections to releasing it? @oeway @FynnBe @k-dominik

### CODE REVIEW

**Comment by k-dominik** [comment]
all for it :+1:

**Comment by FynnBe** [comment]
me too 👍

**Comment by oeway** [comment]
Go ahead! Keep in mind that we can release 0.3.2post0

However, can we merge the two other PRs before we release? @FynnBe Could you take a look?

**Comment by constantinpape** [comment]
All merged, I am waiting for CI to pass on main and then I will merge this one.

**Comment by oeway** [comment]
Thanks, there is another issue, the generated json file's name is wrong. Please hold on and I will fix that.

**Comment by FynnBe** [comment]
> Thanks, there is another issue, the generated json file's name is wrong. Please hold on and I will fix that.

should be this: https://github.com/bioimage-io/spec-bioimage-io/compare/main...FynnBe-patch-1?quick_pull=1

**Comment by constantinpape** [comment]
Ok, I will merge when all tests have passed.

**Comment by FynnBe** [comment]
really not that important, but when checking the links I found another issue: the links to sections that themselves contain a link in the section name did not work on github... trying to fix this here: https://github.com/bioimage-io/spec-bioimage-io/pull/188

**Comment by FynnBe** [comment]
it was such a trivial fix I just went ahead and merged it 
https://github.com/bioimage-io/spec-bioimage-io#model-resource-description-file-specificationhttpsgithubcombioimage-iospec-bioimage-ioblobgh-pagesmodel_spec_latestmd (invalid)
was replaced with 
https://github.com/bioimage-io/spec-bioimage-io#model-resource-description-file-specification (now works)

**Comment by constantinpape** [comment]
Everything green on main, so I merged !

**Pull request merged**
